-- Generated by scripts/schema-snapshot.mjs. Do not edit.
-- Applied migrations: 001_initial.sql, 002_mobile_and_hardening.sql, 003_presence_and_outbox.sql, 004_salesforce_owner_mappings.sql, 005_round_robin_order.sql, 006_service_groups.sql, 007_outbox_leases.sql, 008_assignment_guards.sql, 009_atomic_sessions.sql, 010_email_signin.sql, 011_app_managed_queues.sql, 012_audit_retention_and_walkins.sql, 013_change_notifications.sql, 014_rollover_retention_and_numbers.sql, 015_presence_window.sql

-- table qms.counters
  day date not null
  service_id text not null
  value int4 not null
  constraint counters_day_not_null NOT NULL day
  constraint counters_pkey PRIMARY KEY (day, service_id)
  constraint counters_service_id_fkey FOREIGN KEY (service_id) REFERENCES qms.services(id)
  constraint counters_service_id_not_null NOT NULL service_id
  constraint counters_value_not_null NOT NULL value
  CREATE UNIQUE INDEX counters_pkey ON qms.counters USING btree (day, service_id)

-- table qms.events
  id int8 not null
  ticket_id uuid
  actor_id uuid
  action text not null
  details jsonb not null default '{}'::jsonb
  created_at timestamptz not null default now()
  constraint events_action_not_null NOT NULL action
  constraint events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES qms.users(id)
  constraint events_created_at_not_null NOT NULL created_at
  constraint events_details_not_null NOT NULL details
  constraint events_id_not_null NOT NULL id
  constraint events_pkey PRIMARY KEY (id)
  constraint events_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES qms.tickets(id)
  CREATE INDEX events_created ON qms.events USING btree (created_at)
  CREATE UNIQUE INDEX events_pkey ON qms.events USING btree (id)
  CREATE INDEX events_ticket ON qms.events USING btree (ticket_id, created_at)

-- table qms.lookups
  id uuid not null default gen_random_uuid()
  actor_id uuid not null
  identifier_type text not null
  identifier_value text not null
  customer jsonb not null
  created_at timestamptz not null default now()
  expires_at timestamptz not null default (now() + '00:15:00'::interval)
  constraint lookups_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES qms.users(id)
  constraint lookups_actor_id_not_null NOT NULL actor_id
  constraint lookups_created_at_not_null NOT NULL created_at
  constraint lookups_customer_not_null NOT NULL customer
  constraint lookups_expires_at_not_null NOT NULL expires_at
  constraint lookups_id_not_null NOT NULL id
  constraint lookups_identifier_type_not_null NOT NULL identifier_type
  constraint lookups_identifier_value_not_null NOT NULL identifier_value
  constraint lookups_pkey PRIMARY KEY (id)
  CREATE UNIQUE INDEX lookups_pkey ON qms.lookups USING btree (id)

-- table qms.migrations
  name text not null
  applied_at timestamptz not null default now()
  checksum text
  constraint migrations_applied_at_not_null NOT NULL applied_at
  constraint migrations_name_not_null NOT NULL name
  constraint migrations_pkey PRIMARY KEY (name)
  CREATE UNIQUE INDEX migrations_pkey ON qms.migrations USING btree (name)

-- table qms.notifications
  id int8 not null
  user_id uuid not null
  ticket_id uuid not null
  created_at timestamptz not null default now()
  read_at timestamptz
  constraint notifications_created_at_not_null NOT NULL created_at
  constraint notifications_id_not_null NOT NULL id
  constraint notifications_pkey PRIMARY KEY (id)
  constraint notifications_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES qms.tickets(id)
  constraint notifications_ticket_id_not_null NOT NULL ticket_id
  constraint notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES qms.users(id)
  constraint notifications_user_id_not_null NOT NULL user_id
  CREATE UNIQUE INDEX notifications_pkey ON qms.notifications USING btree (id)

-- table qms.outbox
  id uuid not null default gen_random_uuid()
  ticket_id uuid not null
  kind text not null
  status text not null default 'pending'::text
  attempts int4 not null default 0
  available_at timestamptz not null default now()
  locked_at timestamptz
  last_error text
  provider_reference text
  created_at timestamptz not null default now()
  revision int4 not null default 1
  lease_token uuid
  constraint outbox_attempts_not_null NOT NULL attempts
  constraint outbox_available_at_not_null NOT NULL available_at
  constraint outbox_created_at_not_null NOT NULL created_at
  constraint outbox_id_not_null NOT NULL id
  constraint outbox_kind_check CHECK ((kind = ANY (ARRAY['sms'::text, 'salesforce'::text])))
  constraint outbox_kind_not_null NOT NULL kind
  constraint outbox_pkey PRIMARY KEY (id)
  constraint outbox_revision_not_null NOT NULL revision
  constraint outbox_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text, 'disabled'::text])))
  constraint outbox_status_not_null NOT NULL status
  constraint outbox_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES qms.tickets(id)
  constraint outbox_ticket_id_kind_key UNIQUE (ticket_id, kind)
  constraint outbox_ticket_id_not_null NOT NULL ticket_id
  CREATE UNIQUE INDEX outbox_pkey ON qms.outbox USING btree (id)
  CREATE UNIQUE INDEX outbox_ticket_id_kind_key ON qms.outbox USING btree (ticket_id, kind)

-- table qms.rate_limits
  key text not null
  window_start timestamptz not null
  count int4 not null
  constraint rate_limits_count_not_null NOT NULL count
  constraint rate_limits_key_not_null NOT NULL key
  constraint rate_limits_pkey PRIMARY KEY (key, window_start)
  constraint rate_limits_window_start_not_null NOT NULL window_start
  CREATE UNIQUE INDEX rate_limits_pkey ON qms.rate_limits USING btree (key, window_start)

-- table qms.round_robin
  service_id text not null
  user_id uuid not null
  last_assigned timestamptz not null default now()
  position int8 not null default nextval('qms.round_robin_position'::regclass)
  constraint round_robin_last_assigned_not_null NOT NULL last_assigned
  constraint round_robin_pkey PRIMARY KEY (service_id, user_id)
  constraint round_robin_position_not_null NOT NULL "position"
  constraint round_robin_service_id_fkey FOREIGN KEY (service_id) REFERENCES qms.services(id)
  constraint round_robin_service_id_not_null NOT NULL service_id
  constraint round_robin_user_id_fkey FOREIGN KEY (user_id) REFERENCES qms.users(id)
  constraint round_robin_user_id_not_null NOT NULL user_id
  CREATE UNIQUE INDEX round_robin_pkey ON qms.round_robin USING btree (service_id, user_id)

-- table qms.services
  id text not null
  name text not null
  department text not null
  prefix text not null
  constraint services_department_not_null NOT NULL department
  constraint services_id_not_null NOT NULL id
  constraint services_name_not_null NOT NULL name
  constraint services_pkey PRIMARY KEY (id)
  constraint services_prefix_key UNIQUE (prefix)
  constraint services_prefix_not_null NOT NULL prefix
  CREATE UNIQUE INDEX services_pkey ON qms.services USING btree (id)
  CREATE UNIQUE INDEX services_prefix_key ON qms.services USING btree (prefix)

-- table qms.sessions
  token_hash text not null
  user_id uuid not null
  expires_at timestamptz not null
  created_at timestamptz not null default now()
  constraint sessions_created_at_not_null NOT NULL created_at
  constraint sessions_expires_at_not_null NOT NULL expires_at
  constraint sessions_pkey PRIMARY KEY (token_hash)
  constraint sessions_token_hash_not_null NOT NULL token_hash
  constraint sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES qms.users(id)
  constraint sessions_user_id_not_null NOT NULL user_id
  CREATE INDEX sessions_expiry ON qms.sessions USING btree (expires_at)
  CREATE UNIQUE INDEX sessions_pkey ON qms.sessions USING btree (token_hash)

-- table qms.system_state
  key text not null
  value jsonb not null
  updated_at timestamptz not null default now()
  constraint system_state_key_not_null NOT NULL key
  constraint system_state_pkey PRIMARY KEY (key)
  constraint system_state_updated_at_not_null NOT NULL updated_at
  constraint system_state_value_not_null NOT NULL value
  CREATE UNIQUE INDEX system_state_pkey ON qms.system_state USING btree (key)

-- table qms.tickets
  id uuid not null default gen_random_uuid()
  number text not null
  day date not null
  sequence int4 not null
  request_id uuid not null
  lookup_id uuid not null
  service_id text not null
  status text not null default 'waiting'::text
  customer_id text
  customer_name text not null
  mobile text
  emirates_id text
  passport_number text
  identifier_type text not null
  unit_id text
  unit_name text
  project_name text
  booking_number text
  owner_sf_id text
  manager_sf_id text
  assigned_to uuid
  assigned_at timestamptz
  routing_reason text not null default 'awaiting_agent'::text
  escalated bool not null default false
  created_by uuid not null
  created_at timestamptz not null default now()
  called_at timestamptz
  started_at timestamptz
  closed_at timestamptz
  comments text
  version int4 not null default 1
  public_token uuid not null default gen_random_uuid()
  constraint tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES qms.users(id)
  constraint tickets_created_at_not_null NOT NULL created_at
  constraint tickets_created_by_fkey FOREIGN KEY (created_by) REFERENCES qms.users(id)
  constraint tickets_created_by_not_null NOT NULL created_by
  constraint tickets_customer_name_not_null NOT NULL customer_name
  constraint tickets_day_not_null NOT NULL day
  constraint tickets_day_service_id_sequence_key UNIQUE (day, service_id, sequence)
  constraint tickets_escalated_not_null NOT NULL escalated
  constraint tickets_id_not_null NOT NULL id
  constraint tickets_identifier_type_not_null NOT NULL identifier_type
  constraint tickets_lookup_id_fkey FOREIGN KEY (lookup_id) REFERENCES qms.lookups(id)
  constraint tickets_lookup_id_not_null NOT NULL lookup_id
  constraint tickets_number_not_null NOT NULL number
  constraint tickets_pkey PRIMARY KEY (id)
  constraint tickets_public_token_key UNIQUE (public_token)
  constraint tickets_public_token_not_null NOT NULL public_token
  constraint tickets_request_id_key UNIQUE (request_id)
  constraint tickets_request_id_not_null NOT NULL request_id
  constraint tickets_routing_reason_not_null NOT NULL routing_reason
  constraint tickets_sequence_not_null NOT NULL sequence
  constraint tickets_service_id_fkey FOREIGN KEY (service_id) REFERENCES qms.services(id)
  constraint tickets_service_id_not_null NOT NULL service_id
  constraint tickets_status_check CHECK ((status = ANY (ARRAY['waiting'::text, 'called'::text, 'serving'::text, 'closed'::text, 'no_show'::text])))
  constraint tickets_status_not_null NOT NULL status
  constraint tickets_version_not_null NOT NULL version
  CREATE UNIQUE INDEX one_active_service_per_agent ON qms.tickets USING btree (assigned_to) WHERE ((status = ANY (ARRAY['called'::text, 'serving'::text])) AND (assigned_to IS NOT NULL))
  CREATE INDEX tickets_assigned ON qms.tickets USING btree (assigned_to, status)
  CREATE INDEX tickets_closed_at ON qms.tickets USING btree (closed_at) WHERE (closed_at IS NOT NULL)
  CREATE INDEX tickets_created ON qms.tickets USING btree (created_at)
  CREATE UNIQUE INDEX tickets_day_service_id_sequence_key ON qms.tickets USING btree (day, service_id, sequence)
  CREATE UNIQUE INDEX tickets_pkey ON qms.tickets USING btree (id)
  CREATE UNIQUE INDEX tickets_public_token_key ON qms.tickets USING btree (public_token)
  CREATE INDEX tickets_queue ON qms.tickets USING btree (service_id, status, created_at)
  CREATE UNIQUE INDEX tickets_request_id_key ON qms.tickets USING btree (request_id)

-- table qms.users
  id uuid not null default gen_random_uuid()
  username text not null
  name text not null
  role text not null default 'agent'::text
  password_hash text
  sf_id text
  manager_sf_id text
  services _text not null default '{}'::text[]
  online bool not null default false
  last_seen timestamptz
  counter text not null default ''::text
  enabled bool not null default true
  must_change_password bool not null default true
  created_at timestamptz not null default now()
  email text
  constraint users_counter_not_null NOT NULL counter
  constraint users_created_at_not_null NOT NULL created_at
  constraint users_enabled_not_null NOT NULL enabled
  constraint users_id_not_null NOT NULL id
  constraint users_must_change_password_not_null NOT NULL must_change_password
  constraint users_name_not_null NOT NULL name
  constraint users_online_not_null NOT NULL online
  constraint users_pkey PRIMARY KEY (id)
  constraint users_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'hod'::text, 'manager'::text, 'agent'::text, 'reception'::text, 'customer'::text, 'display'::text])))
  constraint users_role_not_null NOT NULL role
  constraint users_services_not_null NOT NULL services
  constraint users_sf_id_key UNIQUE (sf_id)
  constraint users_username_key UNIQUE (username)
  constraint users_username_not_null NOT NULL username
  CREATE INDEX users_email_lower ON qms.users USING btree (lower(email)) WHERE (email IS NOT NULL)
  CREATE UNIQUE INDEX users_pkey ON qms.users USING btree (id)
  CREATE UNIQUE INDEX users_sf_id_key ON qms.users USING btree (sf_id)
  CREATE UNIQUE INDEX users_username_key ON qms.users USING btree (username)

-- sequence qms.round_robin_position

-- view qms.ticket_view
SELECT t.id,
    t.number,
    t.day,
    t.sequence,
    t.request_id,
    t.lookup_id,
    t.service_id,
    t.status,
    t.customer_id,
    t.customer_name,
    t.mobile,
    t.emirates_id,
    t.passport_number,
    t.identifier_type,
    t.unit_id,
    t.unit_name,
    t.project_name,
    t.booking_number,
    t.owner_sf_id,
    t.manager_sf_id,
    t.assigned_to,
    t.assigned_at,
    t.routing_reason,
    t.escalated,
    t.created_by,
    t.created_at,
    t.called_at,
    t.started_at,
    t.closed_at,
    t.comments,
    t.version,
    s.name AS service_name,
    s.department,
    u.name AS assigned_name,
    u.counter,
    t.public_token
   FROM qms.tickets t
     JOIN qms.services s ON s.id = t.service_id
     LEFT JOIN qms.users u ON u.id = t.assigned_to;

-- trigger notifications_notify
CREATE TRIGGER notifications_notify AFTER INSERT OR UPDATE ON qms.notifications FOR EACH STATEMENT EXECUTE FUNCTION qms.notify_change()

-- trigger tickets_notify
CREATE TRIGGER tickets_notify AFTER INSERT OR UPDATE ON qms.tickets FOR EACH STATEMENT EXECUTE FUNCTION qms.notify_change()

-- trigger tickets_salesforce_outbox
CREATE TRIGGER tickets_salesforce_outbox AFTER INSERT OR UPDATE OF status, assigned_to, comments ON qms.tickets FOR EACH ROW EXECUTE FUNCTION qms.queue_salesforce_change()

-- trigger users_presence_notify
CREATE TRIGGER users_presence_notify AFTER UPDATE ON qms.users FOR EACH ROW WHEN (((old.online IS DISTINCT FROM new.online) OR (old.services IS DISTINCT FROM new.services) OR (old.enabled IS DISTINCT FROM new.enabled) OR (old.counter IS DISTINCT FROM new.counter))) EXECUTE FUNCTION qms.notify_change()

-- function qms.apply_retention(p_identifier_days integer, p_event_days integer)
CREATE OR REPLACE FUNCTION qms.apply_retention(p_identifier_days integer, p_event_days integer)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE anonymised integer:=0; deleted integer:=0; last_run timestamptz;
BEGIN
 PERFORM pg_advisory_xact_lock(1947302);
 SELECT updated_at INTO last_run FROM qms.system_state WHERE key='retention';
 IF last_run IS NOT NULL AND last_run>now()-interval '1 hour' THEN RETURN jsonb_build_object('skipped',true,'lastRun',last_run);END IF;
 IF coalesce(p_identifier_days,0)>0 THEN
  -- Closed tickets older than the period lose the customer's name and
  -- identifiers; the lookup snapshot behind them is redacted once no newer
  -- ticket still refers to it. Unit, project and Salesforce ids stay for reporting.
  WITH done AS (
   UPDATE qms.tickets t SET customer_name='Customer',mobile=NULL,emirates_id=NULL,passport_number=NULL
   WHERE t.closed_at IS NOT NULL AND t.closed_at<now()-make_interval(days=>p_identifier_days)
    AND (t.mobile IS NOT NULL OR t.emirates_id IS NOT NULL OR t.passport_number IS NOT NULL OR t.customer_name<>'Customer')
    AND NOT EXISTS(SELECT 1 FROM qms.outbox o WHERE o.ticket_id=t.id AND o.status IN ('pending','processing'))
   RETURNING t.lookup_id),
  redacted AS (
   UPDATE qms.lookups l SET identifier_value='',customer=(l.customer - 'name' - 'firstName' - 'middleName' - 'lastName' - 'mobile' - 'emiratesId' - 'passportNumber' - 'email')||'{"redacted":true}'::jsonb
   WHERE l.id IN (SELECT lookup_id FROM done) AND NOT (l.customer ? 'redacted')
    AND NOT EXISTS(SELECT 1 FROM qms.tickets t2 WHERE t2.lookup_id=l.id AND (t2.closed_at IS NULL OR t2.closed_at>=now()-make_interval(days=>p_identifier_days)))
   RETURNING l.id)
  SELECT count(*) INTO anonymised FROM done;
 END IF;
 IF coalesce(p_event_days,0)>0 THEN
  DELETE FROM qms.events WHERE created_at<now()-make_interval(days=>p_event_days);
  GET DIAGNOSTICS deleted=ROW_COUNT;
 END IF;
 INSERT INTO qms.system_state(key,value) VALUES('retention',jsonb_build_object('identifierDays',p_identifier_days,'eventDays',p_event_days,'anonymised',anonymised,'deletedEvents',deleted)) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=now();
 IF anonymised>0 OR deleted>0 THEN INSERT INTO qms.events(action,details) VALUES('retention',jsonb_build_object('anonymised',anonymised,'deletedEvents',deleted,'identifierDays',p_identifier_days,'eventDays',p_event_days));END IF;
 RETURN jsonb_build_object('anonymised',anonymised,'deletedEvents',deleted);
END $function$

-- function qms.assign_ticket(p_ticket uuid, p_user uuid, p_reason text, p_actor uuid)
CREATE OR REPLACE FUNCTION qms.assign_ticket(p_ticket uuid, p_user uuid, p_reason text, p_actor uuid DEFAULT NULL::uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE prior uuid;
BEGIN
 SELECT assigned_to INTO prior FROM qms.tickets WHERE id=p_ticket;
 UPDATE qms.tickets SET assigned_to=p_user,assigned_at=CASE WHEN p_user IS NULL THEN NULL ELSE now() END,routing_reason=p_reason,version=version+1 WHERE id=p_ticket;
 IF p_user IS DISTINCT FROM prior THEN
  UPDATE qms.notifications SET read_at=now() WHERE ticket_id=p_ticket AND user_id IS DISTINCT FROM p_user AND read_at IS NULL;
  INSERT INTO qms.events(ticket_id,actor_id,action,details) VALUES(p_ticket,p_actor,'assigned',jsonb_build_object('from',prior,'to',p_user,'reason',p_reason));
  IF p_user IS NOT NULL THEN
   INSERT INTO qms.notifications(user_id,ticket_id) VALUES(p_user,p_ticket);
   INSERT INTO qms.round_robin(service_id,user_id,last_assigned,position) SELECT service_id,p_user,clock_timestamp(),nextval('qms.round_robin_position') FROM qms.tickets WHERE id=p_ticket ON CONFLICT(service_id,user_id) DO UPDATE SET last_assigned=excluded.last_assigned,position=excluded.position;
  END IF;
 END IF;
END $function$

-- function qms.change_password(p_user uuid, p_verified_hash text, p_new_hash text, p_token_hash text)
CREATE OR REPLACE FUNCTION qms.change_password(p_user uuid, p_verified_hash text, p_new_hash text, p_token_hash text)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE current_hash text; allowed boolean;
BEGIN
 SELECT password_hash,enabled INTO current_hash,allowed FROM qms.users WHERE id=p_user FOR UPDATE;
 IF NOT FOUND OR NOT allowed OR current_hash IS DISTINCT FROM p_verified_hash THEN RETURN false; END IF;
 UPDATE qms.users SET password_hash=p_new_hash,must_change_password=false WHERE id=p_user;
 DELETE FROM qms.sessions WHERE user_id=p_user;
 INSERT INTO qms.sessions(token_hash,user_id,expires_at) VALUES(p_token_hash,p_user,now()+interval '8 hours');
 INSERT INTO qms.events(actor_id,action) VALUES(p_user,'password_changed');
 RETURN true;
END $function$

-- function qms.choose_available(p_service text, p_exclude uuid)
CREATE OR REPLACE FUNCTION qms.choose_available(p_service text, p_exclude uuid DEFAULT NULL::uuid)
 RETURNS uuid
 LANGUAGE sql
AS $function$
 SELECT u.id FROM qms.users u LEFT JOIN qms.round_robin rr ON rr.service_id=p_service AND rr.user_id=u.id
 WHERE u.enabled AND u.online AND u.last_seen>now()-interval '45 seconds' AND u.role IN ('agent','manager','hod','admin') AND p_service=ANY(u.services) AND (p_exclude IS NULL OR u.id<>p_exclude)
 AND NOT EXISTS(SELECT 1 FROM qms.tickets t WHERE t.assigned_to=u.id AND t.status IN ('called','serving'))
 ORDER BY rr.position ASC NULLS FIRST,u.created_at,u.id LIMIT 1
$function$

-- function qms.issue_session(p_user uuid, p_verified_hash text, p_token_hash text)
CREATE OR REPLACE FUNCTION qms.issue_session(p_user uuid, p_verified_hash text, p_token_hash text)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE current_hash text; allowed boolean;
BEGIN
 SELECT password_hash,enabled INTO current_hash,allowed FROM qms.users WHERE id=p_user FOR UPDATE;
 IF NOT FOUND OR NOT allowed OR current_hash IS DISTINCT FROM p_verified_hash THEN RETURN false; END IF;
 INSERT INTO qms.sessions(token_hash,user_id,expires_at) VALUES(p_token_hash,p_user,now()+interval '8 hours');
 RETURN true;
END $function$

-- function qms.issue_ticket(p_lookup uuid, p_service text, p_unit text, p_request uuid, p_actor uuid)
CREATE OR REPLACE FUNCTION qms.issue_ticket(p_lookup uuid, p_service text, p_unit text, p_request uuid, p_actor uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE l qms.lookups; c jsonb; unit jsonb; s qms.services; tid uuid; seq integer; visit_day date; ticket_number text; existing qms.tickets; registered boolean; has_units boolean;
BEGIN
 PERFORM pg_advisory_xact_lock(1947301);
 SELECT * INTO existing FROM qms.tickets WHERE request_id=p_request;
 IF FOUND THEN IF existing.created_by<>p_actor THEN RAISE EXCEPTION 'FORBIDDEN'; END IF; IF existing.lookup_id<>p_lookup OR existing.service_id<>p_service OR existing.unit_id IS DISTINCT FROM p_unit THEN RAISE EXCEPTION 'IDEMPOTENCY_CONFLICT';END IF;RETURN (SELECT to_jsonb(v) FROM qms.ticket_view v WHERE id=existing.id);END IF;
 SELECT * INTO l FROM qms.lookups WHERE id=p_lookup AND actor_id=p_actor AND expires_at>now();
 IF NOT FOUND THEN RAISE EXCEPTION 'LOOKUP_EXPIRED';END IF;
 c:=l.customer;
 registered:=coalesce((c->>'registered')::boolean,false);
 has_units:=jsonb_typeof(c->'units')='array' AND jsonb_array_length(c->'units')>0;
 SELECT * INTO s FROM qms.services WHERE id=p_service;
 IF NOT FOUND OR (NOT registered AND p_service<>'general') OR (registered AND has_units AND p_service='general') OR (registered AND NOT has_units AND p_service<>'general') THEN RAISE EXCEPTION 'INVALID_SERVICE';END IF;
 IF p_service='general' AND p_unit IS NOT NULL THEN RAISE EXCEPTION 'UNIT_NOT_ALLOWED';END IF;
 IF p_service<>'general' THEN
  SELECT value INTO unit FROM jsonb_array_elements(c->'units') WHERE value->>'id'=p_unit;
  IF unit IS NULL THEN RAISE EXCEPTION 'UNIT_REQUIRED';END IF;
 END IF;
 IF EXISTS(SELECT 1 FROM qms.tickets t JOIN qms.lookups old ON old.id=t.lookup_id WHERE t.status IN ('waiting','called','serving') AND t.service_id=p_service AND coalesce(t.unit_id,'')=coalesce(p_unit,'') AND ((t.customer_id IS NOT NULL AND t.customer_id=c->>'salesforceId') OR (old.identifier_type=l.identifier_type AND old.identifier_value=l.identifier_value))) THEN RAISE EXCEPTION 'DUPLICATE_VISIT';END IF;
 visit_day:=(now() AT TIME ZONE 'Asia/Dubai')::date;
 INSERT INTO qms.counters(day,service_id,value) VALUES(visit_day,p_service,1) ON CONFLICT(day,service_id) DO UPDATE SET value=qms.counters.value+1 RETURNING value INTO seq;
 ticket_number:=s.prefix||'-'||lpad(seq::text,greatest(3,length(seq::text)),'0');
 -- Numbering restarts every day; a number an earlier day's ticket still shows on the floor is skipped.
 WHILE EXISTS(SELECT 1 FROM qms.tickets t WHERE t.number=ticket_number AND t.day<>visit_day AND t.status IN ('waiting','called','serving')) LOOP
  UPDATE qms.counters SET value=value+1 WHERE day=visit_day AND service_id=p_service RETURNING value INTO seq;
  ticket_number:=s.prefix||'-'||lpad(seq::text,greatest(3,length(seq::text)),'0');
 END LOOP;
 INSERT INTO qms.tickets(number,day,sequence,request_id,lookup_id,service_id,customer_id,customer_name,mobile,emirates_id,passport_number,identifier_type,unit_id,unit_name,project_name,booking_number,owner_sf_id,manager_sf_id,created_by)
 VALUES(ticket_number,visit_day,seq,p_request,p_lookup,p_service,c->>'salesforceId',coalesce(nullif(c->>'name',''),'Walk-in customer'),c->>'mobile',c->>'emiratesId',c->>'passportNumber',l.identifier_type,unit->>'id',unit->>'name',unit->>'project',unit->>'bookingNumber',CASE WHEN p_service LIKE 'crm-%' AND unit ? 'owners' THEN unit->'owners'->p_service->>'ownerId' ELSE unit->>'ownerId' END,CASE WHEN p_service LIKE 'crm-%' AND unit ? 'owners' THEN unit->'owners'->p_service->>'managerId' ELSE unit->>'managerId' END,p_actor) RETURNING id INTO tid;
 INSERT INTO qms.events(ticket_id,actor_id,action) VALUES(tid,p_actor,'issued');
 PERFORM qms.route_ticket(tid,true);
 IF l.identifier_type='mobile' AND registered AND nullif(c->>'mobile','') IS NOT NULL THEN INSERT INTO qms.outbox(ticket_id,kind) VALUES(tid,'sms');END IF;
 RETURN (SELECT to_jsonb(v) FROM qms.ticket_view v WHERE id=tid);
END $function$

-- function qms.notify_change()
CREATE OR REPLACE FUNCTION qms.notify_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
 PERFORM pg_notify('qms_changes',TG_TABLE_NAME);
 RETURN NULL;
END $function$

-- function qms.queue_salesforce_change()
CREATE OR REPLACE FUNCTION qms.queue_salesforce_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
 INSERT INTO qms.outbox(ticket_id,kind,status) VALUES(NEW.id,'salesforce','pending') ON CONFLICT(ticket_id,kind) DO UPDATE SET revision=qms.outbox.revision+1,status=CASE WHEN qms.outbox.status='processing' THEN 'processing' ELSE 'pending' END,attempts=CASE WHEN qms.outbox.status='processing' THEN qms.outbox.attempts ELSE 0 END,available_at=now();
 RETURN NEW;
END $function$

-- function qms.route_due()
CREATE OR REPLACE FUNCTION qms.route_due()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE item record; total integer:=0;
BEGIN
 PERFORM pg_advisory_xact_lock(1947301);
 -- Day rollover: a ticket left waiting or called from a previous Dubai day is
 -- a no-show once it is more than two hours old. Serving tickets are left to
 -- the agent to complete.
 WITH stale AS (UPDATE qms.tickets SET status='no_show',closed_at=now(),version=version+1 WHERE status IN ('waiting','called') AND day<(now() AT TIME ZONE 'Asia/Dubai')::date AND created_at<now()-interval '2 hours' RETURNING id)
 INSERT INTO qms.events(ticket_id,action,details) SELECT id,'no_show','{"reason":"day_rollover"}'::jsonb FROM stale;
 FOR item IN SELECT id FROM qms.tickets WHERE status='waiting' ORDER BY created_at LOOP
  PERFORM qms.route_ticket(item.id,false);total:=total+1;
 END LOOP;
 WITH expired AS (UPDATE qms.users SET online=false WHERE online AND last_seen<now()-interval '45 seconds' RETURNING id)
 INSERT INTO qms.events(actor_id,action,details) SELECT id,'presence_offline','{"reason":"heartbeat_expired"}'::jsonb FROM expired;
 DELETE FROM qms.sessions WHERE expires_at<now();
 DELETE FROM qms.rate_limits WHERE window_start<now()-interval '1 day';
 DELETE FROM qms.lookups l WHERE l.expires_at<now()-interval '1 day' AND NOT EXISTS(SELECT 1 FROM qms.tickets t WHERE t.lookup_id=l.id);
 UPDATE qms.events e SET actor_id=NULL FROM qms.users u
  WHERE e.actor_id=u.id AND u.role='customer' AND u.created_at<now()-interval '1 day'
   AND NOT EXISTS(SELECT 1 FROM qms.sessions s WHERE s.user_id=u.id)
   AND NOT EXISTS(SELECT 1 FROM qms.tickets t WHERE t.created_by=u.id OR t.assigned_to=u.id)
   AND NOT EXISTS(SELECT 1 FROM qms.lookups l WHERE l.actor_id=u.id);
 DELETE FROM qms.users u
  WHERE u.role='customer' AND u.created_at<now()-interval '1 day'
   AND NOT EXISTS(SELECT 1 FROM qms.sessions s WHERE s.user_id=u.id)
   AND NOT EXISTS(SELECT 1 FROM qms.tickets t WHERE t.created_by=u.id OR t.assigned_to=u.id)
   AND NOT EXISTS(SELECT 1 FROM qms.lookups l WHERE l.actor_id=u.id)
   AND NOT EXISTS(SELECT 1 FROM qms.events e WHERE e.actor_id=u.id)
   AND NOT EXISTS(SELECT 1 FROM qms.notifications n WHERE n.user_id=u.id)
   AND NOT EXISTS(SELECT 1 FROM qms.round_robin r WHERE r.user_id=u.id);
 INSERT INTO qms.system_state(key,value) VALUES('worker',jsonb_build_object('lastRun',now(),'checked',total)) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=now();
 RETURN total;
END $function$

-- function qms.route_ticket(p_ticket uuid, p_initial boolean)
CREATE OR REPLACE FUNCTION qms.route_ticket(p_ticket uuid, p_initial boolean DEFAULT false)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE t qms.tickets; owner_user qms.users; assigned_user qms.users; candidate uuid; manager_user qms.users; owner_available boolean;
BEGIN
 SELECT * INTO t FROM qms.tickets WHERE id=p_ticket FOR UPDATE;
 IF t.status<>'waiting' THEN RETURN; END IF;
 SELECT * INTO owner_user FROM qms.users WHERE sf_id=t.owner_sf_id AND enabled AND role IN ('agent','manager','hod','admin');
 owner_available:=owner_user.id IS NOT NULL AND owner_user.online AND owner_user.last_seen>now()-interval '45 seconds' AND t.service_id=ANY(owner_user.services);
 IF (p_initial OR (t.assigned_to IS NULL AND NOT t.escalated)) AND owner_available THEN
  PERFORM qms.assign_ticket(t.id,owner_user.id,CASE WHEN EXISTS(SELECT 1 FROM qms.tickets WHERE assigned_to=owner_user.id AND status IN ('called','serving')) THEN 'owner_busy_five_minute_hold' ELSE 'preferred_owner' END);
  RETURN;
 END IF;
 IF NOT p_initial AND t.assigned_to IS NOT NULL THEN
  SELECT * INTO assigned_user FROM qms.users WHERE id=t.assigned_to;
  IF t.escalated AND t.service_id='collection' AND assigned_user.enabled AND assigned_user.role IN ('manager','hod','admin') AND assigned_user.sf_id=t.manager_sf_id THEN RETURN; END IF;
  IF assigned_user.enabled AND t.service_id=ANY(assigned_user.services) AND assigned_user.online AND assigned_user.last_seen>now()-interval '45 seconds' AND now()<=coalesce(t.assigned_at,t.created_at)+interval '5 minutes' THEN RETURN; END IF;
 END IF;
 IF t.service_id='collection' THEN
  SELECT * INTO manager_user FROM qms.users WHERE sf_id=t.manager_sf_id AND enabled AND role IN ('manager','hod','admin');
  IF manager_user.id IS NOT NULL THEN
   PERFORM qms.assign_ticket(t.id,manager_user.id,CASE WHEN manager_user.online AND manager_user.last_seen>now()-interval '45 seconds' THEN 'escalated_to_manager' ELSE 'manager_offline_attention_required' END);
   UPDATE qms.tickets SET escalated=true WHERE id=t.id;
  ELSE
   IF t.assigned_to IS NOT NULL OR t.routing_reason<>'manager_mapping_missing' THEN PERFORM qms.assign_ticket(t.id,NULL,'manager_mapping_missing'); END IF;
  END IF;
 ELSE
  candidate:=qms.choose_available(t.service_id,t.assigned_to);
  IF candidate IS NOT NULL THEN
   PERFORM qms.assign_ticket(t.id,candidate,CASE WHEN p_initial THEN 'round_robin' ELSE 'reassigned_round_robin' END);
   UPDATE qms.tickets SET escalated=true WHERE id=t.id;
  ELSE
   IF t.assigned_to IS NOT NULL AND (NOT assigned_user.enabled OR NOT(t.service_id=ANY(assigned_user.services)) OR NOT assigned_user.online OR assigned_user.last_seen<=now()-interval '45 seconds') THEN PERFORM qms.assign_ticket(t.id,NULL,'no_available_agent');
   ELSIF t.assigned_to IS NULL AND t.routing_reason<>'no_available_agent' THEN PERFORM qms.assign_ticket(t.id,NULL,'no_available_agent'); END IF;
  END IF;
 END IF;
END $function$

-- function qms.save_user(p_id uuid, p_actor uuid, p_username text, p_name text, p_role text, p_sf_id text, p_manager_sf_id text, p_services text[], p_counter text, p_enabled boolean, p_password text)
CREATE OR REPLACE FUNCTION qms.save_user(p_id uuid, p_actor uuid, p_username text, p_name text, p_role text, p_sf_id text, p_manager_sf_id text, p_services text[], p_counter text, p_enabled boolean, p_password text)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
DECLARE uid uuid;
BEGIN
 PERFORM pg_advisory_xact_lock(1947301);
 IF NOT EXISTS(SELECT 1 FROM qms.users WHERE id=p_actor AND role='admin' AND enabled) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
 IF p_id=p_actor AND (p_role<>'admin' OR NOT p_enabled) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
 IF p_id IS NOT NULL THEN
  IF NOT EXISTS(SELECT 1 FROM qms.users WHERE id=p_id) THEN RAISE EXCEPTION 'USER_NOT_FOUND';END IF;
  IF EXISTS(SELECT 1 FROM qms.tickets WHERE assigned_to=p_id AND status IN ('called','serving') AND (NOT p_enabled OR p_role NOT IN ('admin','hod','manager','agent') OR NOT(service_id=ANY(p_services)))) THEN RAISE EXCEPTION 'AGENT_BUSY';END IF;
  UPDATE qms.users SET username=p_username,name=p_name,role=p_role,sf_id=p_sf_id,manager_sf_id=p_manager_sf_id,services=p_services,counter=p_counter,enabled=p_enabled,password_hash=coalesce(p_password,password_hash),must_change_password=CASE WHEN p_password IS NOT NULL THEN true ELSE must_change_password END,online=CASE WHEN NOT p_enabled THEN false ELSE online END WHERE id=p_id RETURNING id INTO uid;
  IF p_password IS NOT NULL OR NOT p_enabled THEN DELETE FROM qms.sessions WHERE user_id=p_id;END IF;
 ELSE
  IF p_password IS NULL THEN RAISE EXCEPTION 'PASSWORD_REQUIRED';END IF;
  INSERT INTO qms.users(username,name,role,sf_id,manager_sf_id,services,counter,enabled,password_hash) VALUES(p_username,p_name,p_role,p_sf_id,p_manager_sf_id,p_services,p_counter,p_enabled,p_password) RETURNING id INTO uid;
 END IF;
 INSERT INTO qms.events(actor_id,action,details) VALUES(p_actor,'team_updated',jsonb_build_object('id',uid,'username',p_username));
 RETURN uid;
END $function$

-- function qms.save_user(p_id uuid, p_actor uuid, p_username text, p_name text, p_role text, p_sf_id text, p_manager_sf_id text, p_services text[], p_counter text, p_enabled boolean, p_password text, p_email text)
CREATE OR REPLACE FUNCTION qms.save_user(p_id uuid, p_actor uuid, p_username text, p_name text, p_role text, p_sf_id text, p_manager_sf_id text, p_services text[], p_counter text, p_enabled boolean, p_password text, p_email text)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
DECLARE uid uuid; v_email text;
BEGIN
 v_email:=nullif(lower(trim(p_email)),'');
 PERFORM pg_advisory_xact_lock(1947301);
 IF NOT EXISTS(SELECT 1 FROM qms.users WHERE id=p_actor AND role='admin' AND enabled) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
 IF p_id=p_actor AND (p_role<>'admin' OR NOT p_enabled) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
 IF p_id IS NOT NULL THEN
  IF NOT EXISTS(SELECT 1 FROM qms.users WHERE id=p_id) THEN RAISE EXCEPTION 'USER_NOT_FOUND';END IF;
  IF EXISTS(SELECT 1 FROM qms.tickets WHERE assigned_to=p_id AND status IN ('called','serving') AND (NOT p_enabled OR p_role NOT IN ('admin','hod','manager','agent') OR NOT(service_id=ANY(p_services)))) THEN RAISE EXCEPTION 'AGENT_BUSY';END IF;
  UPDATE qms.users SET username=p_username,name=p_name,email=v_email,role=p_role,sf_id=p_sf_id,manager_sf_id=p_manager_sf_id,services=p_services,counter=p_counter,enabled=p_enabled,password_hash=coalesce(p_password,password_hash),must_change_password=CASE WHEN p_password IS NOT NULL THEN true ELSE must_change_password END,online=CASE WHEN NOT p_enabled THEN false ELSE online END WHERE id=p_id RETURNING id INTO uid;
  IF p_password IS NOT NULL OR NOT p_enabled THEN DELETE FROM qms.sessions WHERE user_id=p_id;END IF;
 ELSE
  IF p_password IS NULL THEN RAISE EXCEPTION 'PASSWORD_REQUIRED';END IF;
  INSERT INTO qms.users(username,name,email,role,sf_id,manager_sf_id,services,counter,enabled,password_hash) VALUES(p_username,p_name,v_email,p_role,p_sf_id,p_manager_sf_id,p_services,p_counter,p_enabled,p_password) RETURNING id INTO uid;
 END IF;
 INSERT INTO qms.events(actor_id,action,details) VALUES(p_actor,'team_updated',jsonb_build_object('id',uid,'username',p_username));
 RETURN uid;
END $function$

-- function qms.set_presence(p_user uuid, p_online boolean, p_counter text)
CREATE OR REPLACE FUNCTION qms.set_presence(p_user uuid, p_online boolean, p_counter text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE was boolean;
BEGIN
 PERFORM pg_advisory_xact_lock(1947301);
 IF NOT p_online AND EXISTS(SELECT 1 FROM qms.tickets WHERE assigned_to=p_user AND status IN ('called','serving')) THEN RAISE EXCEPTION 'AGENT_BUSY';END IF;
 SELECT online INTO was FROM qms.users WHERE id=p_user AND enabled;
 UPDATE qms.users SET online=p_online,last_seen=now(),counter=coalesce(p_counter,counter) WHERE id=p_user AND enabled;
 IF FOUND AND was IS DISTINCT FROM p_online THEN
  INSERT INTO qms.events(actor_id,action) VALUES(p_user,CASE WHEN p_online THEN 'presence_online' ELSE 'presence_offline' END);
 END IF;
END $function$

-- function qms.set_queue_member(p_service text, p_user uuid, p_member boolean, p_actor uuid)
CREATE OR REPLACE FUNCTION qms.set_queue_member(p_service text, p_user uuid, p_member boolean, p_actor uuid)
 RETURNS text[]
 LANGUAGE plpgsql
AS $function$
DECLARE result text[];
BEGIN
 PERFORM pg_advisory_xact_lock(1947301);
 IF NOT EXISTS(SELECT 1 FROM qms.users WHERE id=p_actor AND role IN ('admin','hod','manager') AND enabled) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
 IF NOT EXISTS(SELECT 1 FROM qms.services WHERE id=p_service) THEN RAISE EXCEPTION 'INVALID_SERVICE';END IF;
 IF NOT EXISTS(SELECT 1 FROM qms.users WHERE id=p_user AND role IN ('admin','hod','manager','agent')) THEN RAISE EXCEPTION 'USER_NOT_FOUND';END IF;
 IF NOT p_member AND EXISTS(SELECT 1 FROM qms.tickets WHERE assigned_to=p_user AND service_id=p_service AND status IN ('called','serving')) THEN RAISE EXCEPTION 'AGENT_BUSY';END IF;
 UPDATE qms.users
  SET services=CASE WHEN p_member THEN ARRAY(SELECT DISTINCT s FROM unnest(services||ARRAY[p_service]) AS s ORDER BY s) ELSE array_remove(services,p_service) END
  WHERE id=p_user RETURNING services INTO result;
 INSERT INTO qms.events(actor_id,action,details) VALUES(p_actor,'queue_updated',jsonb_build_object('service',p_service,'user',p_user,'member',p_member));
 RETURN result;
END $function$

-- function qms.ticket_action(p_ticket uuid, p_action text, p_actor uuid, p_version integer, p_comment text, p_target uuid)
CREATE OR REPLACE FUNCTION qms.ticket_action(p_ticket uuid, p_action text, p_actor uuid, p_version integer, p_comment text DEFAULT NULL::text, p_target uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE t qms.tickets; u qms.users; target qms.users; privileged boolean;
BEGIN
 PERFORM pg_advisory_xact_lock(1947301);
 SELECT * INTO t FROM qms.tickets WHERE id=p_ticket FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'TICKET_NOT_FOUND';END IF;
 SELECT * INTO u FROM qms.users WHERE id=p_actor AND enabled;privileged:=u.role IN ('manager','hod','admin');
 IF u.id IS NULL OR u.role NOT IN ('agent','manager','hod','admin') OR (NOT privileged AND t.assigned_to IS DISTINCT FROM u.id) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
 IF t.version<>p_version THEN RAISE EXCEPTION 'VERSION_CONFLICT';END IF;
 IF p_action='reassign' THEN
  IF NOT privileged THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
  IF t.status NOT IN ('waiting','called') THEN RAISE EXCEPTION 'INVALID_TRANSITION';END IF;
  SELECT * INTO target FROM qms.users WHERE id=p_target AND enabled AND online AND last_seen>now()-interval '45 seconds' AND t.service_id=ANY(services) AND role IN ('agent','manager','hod','admin');
  IF NOT FOUND THEN RAISE EXCEPTION 'INVALID_ASSIGNEE';END IF;
  IF EXISTS(SELECT 1 FROM qms.tickets WHERE assigned_to=target.id AND status IN ('called','serving') AND id<>t.id) THEN RAISE EXCEPTION 'AGENT_BUSY';END IF;
  UPDATE qms.tickets SET status='waiting',called_at=NULL,escalated=true WHERE id=t.id;
  PERFORM qms.assign_ticket(t.id,target.id,'manager_reassignment',p_actor);
 ELSIF p_action='call' THEN
  IF t.status<>'waiting' THEN RAISE EXCEPTION 'INVALID_TRANSITION';END IF;
  IF NOT(t.service_id=ANY(u.services)) AND NOT coalesce(privileged AND u.sf_id=t.manager_sf_id AND t.service_id='collection',false) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
  IF NOT u.online OR u.last_seen<=now()-interval '45 seconds' THEN RAISE EXCEPTION 'AGENT_UNAVAILABLE';END IF;
  IF EXISTS(SELECT 1 FROM qms.tickets WHERE assigned_to=u.id AND status IN ('called','serving')) THEN RAISE EXCEPTION 'AGENT_BUSY';END IF;
  IF t.assigned_to IS DISTINCT FROM u.id THEN
   IF NOT privileged OR NOT(t.service_id=ANY(u.services)) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;
   PERFORM qms.assign_ticket(t.id,u.id,'manager_call',p_actor);
  END IF;
  UPDATE qms.tickets SET status='called',called_at=now(),version=version+1 WHERE id=t.id;
 ELSIF p_action='start' THEN
  IF t.status<>'called' OR t.assigned_to IS DISTINCT FROM u.id THEN RAISE EXCEPTION 'INVALID_TRANSITION';END IF;
  UPDATE qms.tickets SET status='serving',started_at=now(),version=version+1 WHERE id=t.id;
 ELSIF p_action='close' THEN
  IF t.status IN ('closed','no_show') OR (NOT privileged AND t.status<>'serving') THEN RAISE EXCEPTION 'INVALID_TRANSITION';END IF;
  UPDATE qms.tickets SET status='closed',closed_at=now(),comments=p_comment,version=version+1 WHERE id=t.id;
 ELSIF p_action='no_show' THEN
  IF t.status<>'called' THEN RAISE EXCEPTION 'INVALID_TRANSITION';END IF;
  UPDATE qms.tickets SET status='no_show',closed_at=now(),comments=p_comment,version=version+1 WHERE id=t.id;
 ELSE RAISE EXCEPTION 'INVALID_TRANSITION';END IF;
 INSERT INTO qms.events(ticket_id,actor_id,action,details) VALUES(t.id,p_actor,p_action,jsonb_build_object('comment',p_comment));
 RETURN (SELECT to_jsonb(v) FROM qms.ticket_view v WHERE id=t.id);
END $function$
